name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-pc-windows-msvc
          override: true

      - name: Build binary
        run: |
          cargo build --release
          mkdir artifacts
          copy target\release\Friends-Notifier.exe artifacts\

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/Friends-Notifier.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
